### ISSUE TITLE
E117: Unknown function: Intim_invokeCommand

### ISSUE THREAD

**Issue by snuggles42** [iago-lito/intim#12]
Since some time the intim plugin doesn't work anymore. autocmd entry (below) and calling directly using ":call Intim_invokeCommand ('python', 'python3')" give the same error: "E117: Unknown function: Intim_invokeCommand". The same for other commands like ":call Intim_setLanguage('python')". I already cloned the newest version. Any ideas? Could it be a vim issue?

VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 21 2019 04:10:35)
Included patches: 1-197, 322, 377-378, 550, 649, 651, 703, 706-707
Extra patches: 8.1.1401, 8.1.1382, 8.1.1368, 8.1.1367, 8.1.1366, 8.1.1365, 8.1.1046, 8.1.0613, 8.1.0547, 8.1.0546, 8.1.0544, 8.1.0540, 8.1.0539, 8.1.0538, 8.1.0506, 8.1.0208, 8.1.0206, 8.1.0205, 8.1.0189, 8.1.0177, 8.1.0067, 8.1.0066

**Comment by iago-lito** [comment]
It seems that the plugin isn't loaded at all :\

Can you see `/path/to/my/intim/intim.vim` in the output of `:scriptnames` ?  
Have you recently upgraded vim or your vim plugin manager?  
What is your plugin manager btw?

**Comment by snuggles42** [comment]
Mea culpa. I commented out "execute pathogen#infect()" in my vimrc. How daft to forget about that. X-\ Works again. Thanks so much for your super quick reply. Go on with it. Great work!
