### ISSUE TITLE
Julia support?

### ISSUE THREAD

**Issue by Ottermanns** [iago-lito/intim#13]
I have been using intim for quite some time with R and Python. Really a great plugin. Works (almost) perfectly for me. The only thing I miss is Julia support. That would be my data scientist's dream ;-) Would it be possible to add it? I am afraid I am not experienced enough to contribute to this in a useful way.

**Comment by iago-lito** [comment]
Hi @Ottermanns ! I'm sorry I'm more than a year late because Github is [not sending me notifications](https://stackoverflow.com/q/9186193/3719101) if you're not explicitly pinging me when opening an issue here :\\ What exactly are you expecting from a "Julia support"? My personal usage of intim+Julia looks like
```vim
call IntimSetLanguage('julia')
call Intim_invokeCommand('julia', 'julia --project=. --threads 1')
call Intim_headedExpression('julia', ",ln", "length")
call Intim_postInvokeCommands('julia', ['using Revise'])
" ..etc.
```
(`:help Intim.txt`)
Would anything like this be useful? Or would there still be something missing?

**Comment by alaindanet** [comment]
@iago-lito I can confirm that it works for me!

here is my .vimrc

```vim
autocmd Bufenter *.jl call IntimSetLanguage("julia")
autocmd Bufenter *.jl call Intim_invokeCommand('julia', 'julia --project=. --threads 1')
autocmd Bufenter *.jl call Intim_headedExpression('julia', ",ln", "length")
autocmd Bufenter *.jl call Intim_postInvokeCommands('julia', ['using Revise'])
```

**Comment by Ottermanns** [comment]
Thanks. I will try that. In the meantime I switched to slime. But maybe intim will work also ...

**Comment by iago-lito** [comment]
FWIW @Ottermanns, intim support for Julia help pages have just been introduced in 46ec5a0. You should be able to enjoy it now with anything akin to:
```vim
nmap <F1> <Plug>IntimGetHelpWord
vmap <F1> <Plug>IntimGetHelpSelection
```
Next on the list (whenever I either find spare time or contributors) is to also feature dynamic coloration of variables like intim already does for R and Python :)
