### ISSUE TITLE
IntimSetLanguage: Unknown function

### ISSUE THREAD

**Issue by alaindanet** [iago-lito/intim#2]
Hi,

When I try to set the language syntax, e.g. by typing: 
`call IntimSetLanguage('myLanguage')`
I get:
`E117: Fonction inconnue : IntimSetLanguage`

**Comment by iago-lito** [comment]
Hey! Thanks for reporting. This is an unconsistency between the actual function name (`IntimLanguage`) and the function `IntimSetLanguage` described in the doc.

The doc is right. Should be fixed now with 9202379 :)

**Comment by alaindanet** [comment]
Thank you so much =)
