### ISSUE TITLE
Vundle - Error while running helptags

### ISSUE THREAD

**Issue by alaindanet** [iago-lito/intim#5]
Hi Iago,

your plugin is well handle by [Vundle](https://github.com/VundleVim/Vundle.vim) but struggle when generating the helptags of the plugin:

The log file indicates:
```
[2018-01-29 11:30:28] > Error running :helptags /home/alain/.vim/bundle/intim/doc
```

**Comment by iago-lito** [comment]
Hey. Thank your for reporting.

Intim has not been tuned to be installed *via* Vundle for now. It is supposed to be installed with [`Pathogen`](https://github.com/iago-lito/intim#installation).

As a consequence, it is quite likely that using Vundle to install Intim will cause warnings, or errors, or undefined behaviour. (in your case for instance: failure of doc-generation)

I suggest you use the recommended installation procedure. [`Pathogen`](https://github.com/tpope/vim-pathogen) is super easy to install and to use.

However, I'll leave this issue open as a good first issue for anyone feeling like porting Intim's installation procedure to [Vundle](https://github.com/VundleVim/Vundle.vim), which I don't know much. Feel free to contribute :)

**Comment by alaindanet** [comment]
`:heptags ~/.vim/bundle/intim/doc` returns:
![intim_helptags_error](https://user-images.githubusercontent.com/11349327/35516138-46e53752-050b-11e8-96d8-ff025ab33169.png)

I think that it is not a Vundle problem but that several tags are duplicated in your doc.

In the documentation, the pattern `*tag*` should be reserved and not used elsewhere in the documentation.

**Comment by alaindanet** [comment]
`:heptags ~/.vim/bundle/intim/doc` returns:
![intim_helptags_error](https://user-images.githubusercontent.com/11349327/35516138-46e53752-050b-11e8-96d8-ff025ab33169.png)

I think that it is not a Vundle problem but that several tags are duplicated in your doc.

In the documentation, the pattern `*tag*` should be reserved and not used elsewhere.
I can handle it.

**Comment by alaindanet** [comment]
I have created a pull request which fix the errors returned by `helptags`

**Comment by iago-lito** [comment]
Cheers for that. I'll close this issue as soon as your pr is ready to be merged :)

**Comment by iago-lito** [comment]
If you can confirm that this fix is enough to make intim fully Vundle-compatible, feel free to document a small "Vundle" entry in `README.md` [installation](https://github.com/iago-lito/intim#installation) section 0:)

**Comment by iago-lito** [comment]
Well, #8 nailed it. Cheers ♡
