### ISSUE TITLE
Intim option calls fail: `call Intim_*()`

### ISSUE THREAD

**Issue by iago-lito** [iago-lito/intim#6]
Problem forked from #3. **Any `.vimrc` call to an `Intim_<option>` seems to fail.**

@alaindanet I cannot reproduce your problem yet. Let's try digging this out :)

- Can you post the output of `$ vim --version`?

- Is your image of Intim up-to-date? *I.e.* what's the output of 
    ```
    $ cd ~/.vim/bundle/intim
    $ git rev-parse HEAD
    ```
- Does a call to `:call Intim_invokeCommand('python', 'sage')` from Vim command mode also throws an `E117`, or is it just when you start vim?

- Does slacking other functions in your `.vimrc`, like `call IntimSetLanguage('python')` or `call call Intim_hotkeys('python', 'ii', '* += 1')` for instance, also produces `E117` errors?

Thank you for your patience.

**Comment by alaindanet** [comment]
Thank you so much for your help!

Here is the output of `vim --version`:[vim_version_output.txt](https://github.com/iago-lito/intim/files/1673799/vim_version_output.txt)

2. Intim up-to-date ?
```
cd ~/.vim/bundle/intim && git rev-parse HEAD                                                      
e91db2ea12e08e86bb08005151c1cdde4b0167cd
```
3. Does Intim function call always drop errors ? Yes
```
:call Intim_invokeCommand('python', 'sage')
Erreur détectée en traitant function Intim_invokeCommand :
ligne    1 :
E117: Fonction inconnue : <SNR>29_set_invokeCommand
```
4. Is it the case with other functions ? 
- `:call IntimSetLanguage('python')` does not throw an error
- `:call Intim_hotkeys('python', 'ii', '* += 1')` neither

**Comment by iago-lito** [comment]
Well..

1. We are using the same vim version, so no problem on this side

2. Surprisingly e91db2ea12e08e86bb08005151c1cdde4b0167cd is.. *not!* a commit from this repo :D I think you've [forked Intim](https://github.com/alaindanet/intim) to add automatic `sage` filetype detection. There is no problem with that. However, don't forget to post a [pull request](https://github.com/iago-lito/intim/pulls) if you wish your changes to be merged into Intim's repo, and not to miss further updates ;)

3. Well, that's interesting. Maybe something has been broken with function definition macro when adding the hook in 106a9c6a4e0253ece3852a2e77249dae9c664120. I've tried making it cleaner with 72286d27e550a0ccb38153206ee85e76ebdd0ce7.

4. This confirms my hypothesis about the macro for option setting definition being broken by the hook, because global options and dictionnary options seem not affected.

But I still cannot reproduce. Would you please:

- check whether the problem persists in 72286d27e550a0ccb38153206ee85e76ebdd0ce7.

- If yes, post the output of:
    - `echo <SNR>29_setHook_invokeCommand('python', 'python')`
        - (expect `0` or `E117`)
    - `echo <SNR>29_set_postLaunchCommands('python', [''])`
        - (expect error `E117`)
    - `echo <SNR>29_setHook_postLaunchCommands('python', [''])`
        - (expect `0` or `E117`)

Thank you for your patience.

**Comment by alaindanet** [comment]
The previous commands do not report any errors anymore!

**Comment by iago-lito** [comment]
Do you mean that 72286d27e550a0ccb38153206ee85e76ebdd0ce7 fixed it? If yes, I'll close the issue.

**Comment by alaindanet** [comment]
Yes!

**Comment by alaindanet** [comment]
Yes!
